---
- hosts: all
  become: yes
  tasks:

  - name: host name of ansible node 
    command: hostname -f
    register: myresult

  - name: display result
    debug:
      msg: "{{myresult}}"

  - name: IP addr of ansible node 
    command: ifconfig
    register: myresult2

  - name: display result
    debug:
      msg: "{{myresult2}}"

