---
- hosts: webappserver
  become: yes
  tasks:
  - name: ping all devices
    ping:

  - name: i want to install git on ubuntu node
    apt:
      name: "{{mygitvar}}"
      state: present

  - name: i want to install wget on ubuntu node
    apt:
      name: "{{mywgetvar}}"
      state: absent

  - name: i want to install webserver on ubuntu node
    apt:
      name: "{{myapachevar}}"
      update_cache: yes 
      state: absent
    when: ansible_os_family == "Debian"