---
- hosts: all
  become:
  tasks:
  - name: install multiple packages
    apt:
      name: "{{ item }}"
      state: absent
    ignore_errors: yes
    
    loop:
      - git
      - wget
      - tree
      - apache2
    