---
- hosts: all
  become: yes
  vars:
    var1: wget
    var2: tree
    var3: apache2

  tasks:
  - name: display var1
    debug:
      msg: "{{var1}}"

  - name: display var2
    debug:
      msg: "{{var2}}"

  - name: display var3
    debug:
      msg: "{{var3}}"

