---
- hosts: all
  become: yes
  tasks:
  - name: install apache2
    apt:
      name: "{{myapachevar}}"
      state: present
    
  - name: install java
    apt:
      name: "{{myjavaappnew}}"
      state: present

